# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=20)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=500)),
                ('isbn', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
