# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20171007_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
